name: Functions
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:    
          CONTAINS_ARRAY_FUNC: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}
