name: Status Check Functions
on: push
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "Failed condition"
        if: ${{ failure() }}
      - run: echo "Successed condition"
        if: ${{ success() }}
